#!/bin/bash

# Copyright (C) 2015 Associated Universities, Inc. Washington DC, USA.
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
# General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.
#
# Correspondence concerning GBT software should be addressed as follows:
# GBT Operations
# National Radio Astronomy Observatory
# P. O. Box 2
# Green Bank, WV 24944-0002 USA

# WARNING: This script will ruthlessly murder any process whose name matches the strings "hashpipe" or "vegasFitsWriter"
# WARNING: This script relies on a custom "pkill" script; it is probably not portable

if [ "$HOSTNAME" = "west" ]; then
    echo "> Killing all instances of hashpipe and vegasFitsWriter owned by the current user:"
    pkill "hashpipe"
    pkill "vegasFitsWriter"
    echo ""
    clean_ipc

    echo "> Resetting control FIFOs"
    cat /dev/null > /tmp/tchamber/fake_gpu_control
    cat /dev/null > /tmp/tchamber/vegas_fits_control

    if [ -e "/tmp/tchamber/sim1fits/JUNK/VEGAS/*.fits" ]; then
        rm /tmp/tchamber/sim1fits/JUNK/VEGAS/*.fits
    else
        echo ">   No *.fits files to remove"
    fi
else
    echo "> Invalid host: $HOSTNAME"
fi



