#!/bin/bash

hashpipe_check_status -k DATADIR -s '/tmp'
#hashpipe_check_status -k DATADIR -s '/tmp/tchamber/sim1fi
# hashpipe_check_status -k DATADIR -s '/lustre/gbtdata'
hashpipe_check_status -k NUMPHASES -i 1
hashpipe_check_status -k NUMPHASE -i 1
hashpipe_check_status -k NUMCHAN -i 1
hashpipe_check_status -k NUMCHANS -i 1
hashpipe_check_status -k SCANLEN -i 5
hashpipe_check_status -k NSUBBAND -i 1
hashpipe_check_status -k NUMSTOKE -i 1

